import PREFIXES from '../actionTypePrefixes'


const NAMESPACE = 'REGIONS'

export const GET_REGIONS_TRIGGER = `${PREFIXES.TRIGGER}/${NAMESPACE}:GET_REGIONS`
export const GET_REGIONS_REQUEST = `${PREFIXES.REQUEST}/${NAMESPACE}:GET_REGIONS`
export const GET_REGIONS_SUCCESS = `${PREFIXES.SUCCESS}/${NAMESPACE}:GET_REGIONS`
export const GET_REGIONS_FAILURE = `${PREFIXES.FAILURE}/${NAMESPACE}:GET_REGIONS`
export const GET_REGIONS_FULFILL = `${PREFIXES.FULFILL}/${NAMESPACE}:GET_REGIONS`

export const RESET_REGIONS = `${NAMESPACE}:RESET_REGIONS`

export const GET_COUNTRIES_BY_REGION_TRIGGER = `${PREFIXES.TRIGGER}/${NAMESPACE}:GET_COUNTRIES_BY_REGION`
export const GET_COUNTRIES_BY_REGION_REQUEST = `${PREFIXES.REQUEST}/${NAMESPACE}:GET_COUNTRIES_BY_REGION`
export const GET_COUNTRIES_BY_REGION_SUCCESS = `${PREFIXES.SUCCESS}/${NAMESPACE}:GET_COUNTRIES_BY_REGION`
export const GET_COUNTRIES_BY_REGION_FAILURE = `${PREFIXES.FAILURE}/${NAMESPACE}:GET_COUNTRIES_BY_REGION`
export const GET_COUNTRIES_BY_REGION_FULFILL = `${PREFIXES.FULFILL}/${NAMESPACE}:GET_COUNTRIES_BY_REGION`

export const RESET_COUNTRIES_BY_REGION = `${NAMESPACE}:RESET_COUNTRIES_BY_REGION`

export const GET_COUNTRY_BY_NAME_TRIGGER = `${PREFIXES.TRIGGER}/${NAMESPACE}:GET_COUNTRY_BY_NAME`
export const GET_COUNTRY_BY_NAME_REQUEST = `${PREFIXES.REQUEST}/${NAMESPACE}:GET_COUNTRY_BY_NAME`
export const GET_COUNTRY_BY_NAME_SUCCESS = `${PREFIXES.SUCCESS}/${NAMESPACE}:GET_COUNTRY_BY_NAME`
export const GET_COUNTRY_BY_NAME_FAILURE = `${PREFIXES.FAILURE}/${NAMESPACE}:GET_COUNTRY_BY_NAME`
export const GET_COUNTRY_BY_NAME_FULFILL = `${PREFIXES.FULFILL}/${NAMESPACE}:GET_COUNTRY_BY_NAME`

export const RESET_COUNTRY_BY_NAME = `${NAMESPACE}:RESET_COUNTRY_BY_NAME`
